language: ruby

rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10

env:
  global:
    - secure: "nQbHwp3VnoG3hQwZodqvpjWV774prBSRrv8IUKY79c8gfC/XV/fat25iFQoipj2mvtaAc2ydFH+1HkgsbM+Tn6CTLK1pR9KnRYZDkRQ1uiOzyxr7OAVbo+wkJSSb2HeUeVFkngttv/8dGZtvlaGOYxar5B9OtG9qeQWcrcunZ4m8Quxoudxo7FLLeBgcwZVnLH54Ii/DNr9pmzfhaB4/HH4PLldm9e/UvCCaB+9sXCUV61A7xJL6tTKsadRR1vpbaX2t7tPQ3edj/x844/nQsDeid6o7Dh4vPRc7fFfbLBag2lhQh9K3KJ9JAGGQHTxipWGYLO8pQ4oQsWs7Tv4zZmpR53oGpMLRl1HwLC45gkn22Ys6WuSmM6PdutA8nukeRsEMhtinJ8JYD7NEdecFdoiRqNY7CD36hyhwr64dK0tYxjvKOkRrgcYP/uPZcEWnABwTI2CmKHUM64kRnjsMV9rjKD9Jm/cOOKxiuiK2ujH2kH1+xKsfmjxmE3VUkDMNyngsLaWGg1RzvdDBdwD5eP0bj89tI74vp8gm62T5PgaJ5Xna9rNUOfdqxD049XAhTWFkGmfWLMWW2Xrz4uz3rIJEWn4iEM+4b+dwV1fdlrqdRZ1qLfj0ixPwU0Z4XDrnhfO2W4glQP4Q6qi5f8jZTROyzlVc+TCaQRKmrCeH3b8="

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"

script:
  - bundle exec rspec

after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    secure: Li85s+8nvrqSK8pDjWfsQdC1MLBUGcp5f46OHVD6BRcz4faEwg251lbazyT9Uo4FDSEgLD7mhq7ZO0pST0gNkS6tNZNqnC4oPA22bzFf36jffzxFku4eBNq6IC2neWPnwsIuXXk4qncACSsuSBmznZ8pH4DZkEAiSmFYfaHrNZLfO0uM0zvdC04zXd80ZAdexW+u8ejlpI9Dx1a9SrF1j7X+e2t933yx+j+hvmY+q4bO4N/uHHQIS/YnTdykVSmlLQ9YPT3OI+yX7aciYvI5wtEbOb5uT9XaxT4MHAPIwEx2jnBHCChZRPxkafx+DxpH0e1t6NXahlZkrEiVbFfBLJgr12gx4tZBsOsYuCep0KUURu4i41aQPL3l8JOOvlwaDOE6XYWOqLIZy13SFh33owIqalFqN6u9s1cMUOR1TMbQFq2jpn1kWYXjj/YpY+/K8cSIi7ijoPaCtIlqYk+taQ7EKeZsb6lcEUIlpOLyh4YHk+dTj2U/j7IiTd+SJ5gzJxNU8RitovA8qrzDh36mJevjdSSQIwfZKhweUK/7MUDk2i5JU9ptzvjUy6p3k5hfeNO160RQoU7Yaey6xPPd2eAofkN43PRNWy4xC1CH6YVAUUGKgp7Ci+4Ky4lwBxhpJ1BjRzhjwb8E/i3YBQM4E/AUZbKPbLRZB9pwnVAdCX4=
